add a 'gradlew :python:thin_wheel' task that will build 'python/pjrm-1.11.0-py3-none-any.whl'
deshaw/pjrmi pull request #1
Opened 2023-05-23 12:15 UTC by mattip

Step one in uploading a wheel to PyPI for the project: create a version-and-platform-agnostic wheel that contains 
- `pjrmi/__init__.py`
- `pjrmi/_config.py
- `pjrmi/_util.py`
- `pjrmi/lib/pjrmi.jar`

This uses `gradlew :python:thin_wheel` to build the `jar`, and then the standards-compliant `pyproject.toml` to build the wheel via `hatchling`. The reviewers should take a look at the classifiers table to make sure it is accurate, I guessed some of the values

Steps two and three are 
- documentation to clearly state installing a JRE must be done outside of installing pjrme, 
- a github action to create the wheel as an artifact

2023-05-24 17:54 UTC, mattip commented
It seems the repo is set up to require approval before running CI.

2023-05-24 17:57 UTC, iamsrp-deshaw commented
It looks like this was just pushed but it was still pending my review; there are some issues with the commit which need to be addressed (and which require some work on my side).

srp

2023-05-24 18:28 UTC, mattip commented
Do you want to go slower: should I move the second commit (updates the action) to a different branch?

2023-05-24 18:41 UTC, iamsrp-deshaw commented
Just want to make sure that changes have been reviewed before they are pushed. I'm spread a little thin right now and so wasn't getting to the review in a timely fashion, and probably should have flagged as such. Usually I try to do reviews within 12hrs if I can, but this one required some mechanics to happen on my side.

2023-05-25 04:40 UTC, iamsrp-deshaw requested changes
Some general thoughts:
- It could do with more comments, in both files. There's a number of "magic" things going on in these files which are not obvious to a non-SME.
- Current comments need to be fixed in places.
- Some formatting nitpicks, mainly about consistency.
- Naming seems off and/or inconsistent in places.

The lack of / issues with comments is the main one for me. I need to know what's going on in the event that I need to make future changes to the code and/or debug issues with it.

All that being said, thanks for making these changes. Please don't let my overly-prescriptive code review imply that I don't appreciate it!

Cheers,

srp

2023-05-25 04:40 UTC, iamsrp-deshaw commented on python/pyproject.toml
> +build-backend = "hatchling.build"
Can you comment what "hatchling" is and what it's doing here?

2023-05-25 04:40 UTC, iamsrp-deshaw commented on python/pyproject.toml
> +  ]
Overly indented closing `]`; inconsistent with other code.

2023-05-25 04:40 UTC, iamsrp-deshaw commented on python/pyproject.toml
> +  ]
Ditto overly-indented `]`.

2023-05-25 04:40 UTC, iamsrp-deshaw commented on python/pyproject.toml
> +# which is still in draft
Unbreak these lines?

2023-05-25 04:40 UTC, iamsrp-deshaw commented on python/pyproject.toml
> +#authors = [{name = "D.E.Shaw"}]
`"D. E. Shaw & Co LP"`

2023-05-25 04:40 UTC, iamsrp-deshaw commented on python/pyproject.toml
> +#    {name = "D.E.Sahw", email="someone@deshaw.com"},
`    {name = "D. E. Shaw & Co LP", email="pjrmi@deshaw.com"},`

2023-05-25 04:40 UTC, iamsrp-deshaw commented on python/pyproject.toml
> +    'Programming Language :: Python :: 3.11',
Are these subversion numbers consistent with the `3.6` requirement above?

2023-05-25 04:40 UTC, iamsrp-deshaw commented on python/build.gradle
> +task thin_wheel() {
Comment how the `thin_wheel` differs from the `wheel`.

2023-05-25 04:40 UTC, iamsrp-deshaw commented on python/build.gradle
> +            commandLine "python", "setup.py", "bdist_wheel"
Should this be `python3` to be consistent with use of `pip3` elsewhere?

2023-05-25 04:40 UTC, iamsrp-deshaw commented on .github/workflows/wheel.yml
>  # This is a basic workflow to help you get started with Actions.
Should this be called `thin_wheel.yml`, to be consistent with what's it's doing? What happens when/if we want to later actually build the full wheel? Or is it the case that this workflow will be building all the potential wheel types?

2023-05-25 04:40 UTC, iamsrp-deshaw commented on .github/workflows/wheel.yml
>  # To be filled in as part of https://github.com/deshaw/pjrmi/pull/1
This comment can be removed now.

2023-05-25 04:40 UTC, iamsrp-deshaw commented on .github/workflows/wheel.yml
> +  build_wheel:
`build_thin_wheel`?

2023-05-25 04:40 UTC, iamsrp-deshaw commented on .github/workflows/wheel.yml
>    # This workflow contains a single job called "build"
Comment no longer matches the code.

2023-05-25 04:40 UTC, iamsrp-deshaw commented on .github/workflows/wheel.yml
> +      - uses: actions/upload-artifact@3
What is this magic `actions/upload-artifact@3`? Comment it?

2023-05-25 05:33 UTC, mattip commented on python/pyproject.toml
> +build-backend = "hatchling.build"
There are a number of projects that build a wheel. The one used to make the full wheel is setuptools, which uses distutils underneath to compile a c-extension. This pyproject.toml uses a different one: [hatch](https://hatch.pypa.io/latest/), whose tool is called `hatchling`. Here I use `pip wheel` (which uses the `pyproject.toml` file, finds the `build-system`, downloads and installs hatch, and builds the wheel with `hatchling`) to build the thin wheel, and leave the existing `python setup.py` workflow untouched: it can still be used to build a "fat wheel".

2023-05-25 05:36 UTC, iamsrp-deshaw commented on python/pyproject.toml
> +build-backend = "hatchling.build"
Adding a link to `hatch` and saying why we use it (e.g. vs another build system) would be good. If, say, I want to use a different one in the future, then knowing the implications of doing so is handy. E.g. `hatch` might handle something particularly well which, say, `madeup-build-systemname` does not.

2023-05-25 05:46 UTC, mattip commented on python/pyproject.toml
> +    'Programming Language :: Python :: 3.11',
good catch, I will add the missing versions. This is "just" textual information displayed on the PyPI page and used by PyPI indexing, pip will use the `requirement` to choose a version to install.

2023-05-25 05:49 UTC, mattip commented on python/build.gradle
> +            commandLine "python", "setup.py", "bdist_wheel"
OK

2023-05-25 05:50 UTC, mattip commented on .github/workflows/wheel.yml
>  # This is a basic workflow to help you get started with Actions.
I think it is OK as-is and will prevent needing to change the name when you decide to use the full wheel.

2023-05-25 05:53 UTC, mattip commented on .github/workflows/wheel.yml
> +      - uses: actions/upload-artifact@3
It will upload the artifact to github so you can test it, or manually transfer it to PyPI. There is a lot of automation possible via github actions: we could add a workflow so that tagging the repo with a release tag automatically uploads the wheel to PyPI, but that is a bit much for now I think.

2023-05-25 06:07 UTC, mattip commented
> Please don't let my overly-prescriptive code review

All good. That is what code review is for.

2023-05-25 15:38 UTC, iamsrp-deshaw commented on .github/workflows/wheel.yml
> +      - uses: actions/upload-artifact@3
Understood. I was mainly concerned that the text was non-obvious. E.g. why `actions/upload-artifact@3` and not `actions/upload-artifact@7`? Possibly this is a bit of syntax which folks generally understand and, being new to this, I just don't. I still like to have fairly verbosely commented code though, based on the assumption that future editors of it will not be me. (See `__init__.py` for examples of my egregious verbosity.)

2023-05-25 16:11 UTC, iamsrp-deshaw commented
Some minor nitpick comments for the review commits, but nothing substantive.

2023-05-28 07:11 UTC, mattip commented on .github/workflows/wheel.yml
> +      - uses: actions/upload-artifact@3
That is version 3 of the [actions/upload-artifact](https://github.com/actions/upload-artifact#readme) task (now I see it should be `v3` not just `3`). This is part of the github action syntax.

2023-05-30 23:21 UTC, iamsrp-deshaw requested changes
One minor request for a comment but, otherwise, I think this is probably done.

srp

2023-05-30 23:21 UTC, iamsrp-deshaw commented on .github/workflows/wheel.yml
> +      - uses: actions/upload-artifact@v3
Can we add a small comment saying something like:
```
See https://github.com/actions/upload-artifact#readme
```
just so folks (read "I") know where to look here?

2023-05-31 06:56 UTC, mattip commented
> I think this is probably done

Could you approve the workflow so the PR will run? That should produce an artifact that you can check.

2023-05-31 19:22 UTC, iamsrp-deshaw requested changes
Looks like the workflow failed, is there a missing `name =` in the `toml` file?

srp

2023-05-31 19:22 UTC, iamsrp-deshaw commented on python/pyproject.toml
> +    {"D. E. Shaw & Co LP", email="pjrmi@deshaw.com"},
> pip._vendor.tomli._parser.TOMLDecodeError: Expected "=" after a key in a key/value pair (at line 23, column 26)
>
Should this be `name = "D. E. Shaw & Co LP"`?

2023-05-31 20:21 UTC, mattip commented on python/pyproject.toml
> +    {"D. E. Shaw & Co LP", email="pjrmi@deshaw.com"},
Thanks. It needs approval again to run.

2023-05-31 20:34 UTC, mattip commented
Please try again?

2023-05-31 20:46 UTC, mattip commented
Clicking on [the "Summary"](https://github.com/deshaw/pjrmi/actions/runs/5137434199?pr=1), there is an artifact at the bottom of the page: [wheel](https://github.com/deshaw/pjrmi/suites/13283010105/artifacts/724806727) which is a zip file containing the wheel.

Once this is merged we can discuss next steps around documenting how to use the wheel.

2023-05-31 22:29 UTC, iamsrp-deshaw commented
It looks like the zip file only contains the Python files, not the JAR. Maybe the JAR build failed and/or could not be included because it depends on compiling JNI artifacts?

srp

2023-06-01 06:27 UTC, mattip commented
Sorry, I missed that the jar file needs to be created/copied into the proper position.

2023-06-01 13:47 UTC, iamsrp-deshaw commented
That looks to have worked!

2023-06-02 00:23 UTC, iamsrp-deshaw commented
Confirmed that this works on a generic Ubuntu box! Squash and merge next?

srp

2023-06-02 00:47 UTC, iamsrp-deshaw commented
Oh, actually. The wheel needs `snappy` to be installed to work. Is it easy to make that part of the dependencies so that `pip install` gets it installed too?

2023-06-02 05:39 UTC, mattip commented
>  The wheel needs `snappy`

Done.

2023-06-02 16:37 UTC, iamsrp-deshaw requested changes
Syntax error in the recent change?

srp

2023-06-02 16:37 UTC, iamsrp-deshaw commented on python/pyproject.toml
> +    snappy
Does this need `""`s around it?
```
pip._vendor.tomli._parser.TOMLDecodeError: Invalid value (at line 18, column 5)
```

2023-06-04 07:17 UTC, mattip commented on python/pyproject.toml
> +    snappy
yes sorry. I pushed a fix, now when installing the wheel I get
```
Installing collected packages: snappy-manifolds, pypng, plink, low-index, \
    knot-floer-homology, cypari, spherogram, FXrays, snappy, pjrmi
```

2023-06-04 07:45 UTC, iamsrp-deshaw commented
Okay, definitely happier now.

What are the next steps to have the resultant pjrmi....whl file upload to PyPI? There were a lot of extra packages bundled in the `wheel.zip` file, and I presume we only want to load our pjrmi...whl file and not the entire `wheel.zip` file's contents. 

Thanks!

srp

2023-06-04 09:26 UTC, mattip commented
> What are the next steps to have the resultant pjrmi....whl file upload to PyPI? 

Someone must log on to https://pypi.org/ and upload the wheel. That should do it. We can automate the process at a later stage. If you want to test it out, there is https://test.pypi.org/, here is [more documentation](https://packaging.python.org/en/latest/guides/using-testpypi/)

> There were a lot of extra packages bundled in the wheel.zip file, and I presume we only want to load our pjrmi...whl file and not the entire wheel.zip file's contents.

Should be fixed in the last commit

2023-06-05 05:16 UTC, iamsrp-deshaw commented
Confirmed the wheel looks good now. I've pinging folks on my side about PyPI next steps.

srp

2023-06-05 21:10 UTC, mattip commented
Cool. Feel free to merge this, and then we can continue improving it in further PRs.

2023-06-06 05:20 UTC, merged

2023-06-06 05:21 UTC, iamsrp-deshaw commented
Done!

2023-06-07 04:14 UTC, iamsrp-deshaw commented
BTW, at some point I would like to explore being able to do `pip install` via the github link directly, so that folks can get the C++ extensions etc. Hopefully this is simple enough, once they have the requisites apt/yum installed. That can be a "part 2" of this project though.